; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.0-beta3"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.6+3-dev"

projects[apachesolr_views][subdir] = "contrib"
projects[apachesolr_views][version] = "1.0-beta2"
projects[apachesolr_views][patches][] = "https://drupal.org/files/use_arguments-1750952-13.patch"

projects[service_links][subdir] = "contrib"
projects[service_links][version] = "2.2"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0-beta3"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta6"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[db_maintenance][subdir] = "contrib"
projects[db_maintenance][version] = "1.1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.3"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0-rc3"

projects[expire][subdir] = "contrib"
projects[expire][version] = "2.0-rc3"

projects[facetapi_slider][subdir] = "contrib"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "4e0a52349a3f97b346622cda2e0e9ceb24787604"
projects[field_collection][patches][] = "https://drupal.org/files/issues/field_collection-non-object-field_collection_field_get_entity-1880312-9.patch"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1+62-dev"

projects[kaltura][subdir] = "contrib"
projects[kaltura][version] = "2.0"
projects[kaltura][patches][] = "https://drupal.org/files/kaltura-undefined_variable-1547186.patch"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.7"

projects[fivestar][subdir] = "contrib"
projects[fivestar][version] = "2.0-alpha2"

projects[flag][subdir] = "contrib"
projects[flag][version] = "2.0"

projects[flexslider][subdir] = "contrib"
projects[flexslider][version] = "1.0-rc3"

projects[forward][subdir] = "contrib"
projects[forward][version] = "2.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[homepage][download][type] = ""
projects[homepage][download][url] = ""
projects[homepage][type] = "module"
projects[homepage][subdir] = "mediabase/features"
projects[homepage][version] = "1.0"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.11"

projects[i18nviews][subdir] = "contrib"
projects[i18nviews][version] = "3.x-dev"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[json2][subdir] = "contrib"
projects[json2][version] = "1.1"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc4"

projects[mediabase][type] = "module"
projects[mediabase][download][type] = "git"
projects[mediabase][download][url] = "https://github.com/shanti-uva/drupal_mediabase.git"
projects[mediabase][download][branch] = "newtheme"
projects[mediabase][download][revision] = "ee81fc917e513326609bde13b150dc2deff7305b"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[media_listings][download][type] = ""
projects[media_listings][download][url] = ""
projects[media_listings][type] = "module"
projects[media_listings][subdir] = "mediabase/features"
projects[media_listings][version] = "1.0-alpha1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[media_services][download][type] = ""
projects[media_services][download][url] = ""
projects[media_services][type] = "module"
projects[media_services][subdir] = "mediabase/features"
projects[media_services][version] = "1.0-alpha1"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[my_content][download][type] = ""
projects[my_content][download][url] = ""
projects[my_content][type] = "module"
projects[my_content][subdir] = "mediabase/features"
projects[my_content][version] = "1.0-alpha2"

projects[nice_menus][subdir] = "contrib"
projects[nice_menus][version] = "2.5"

projects[og][subdir] = "contrib"
projects[og][version] = "1.5"

projects[og_views][subdir] = "contrib"
projects[og_views][version] = "1.0"

projects[pagerer][subdir] = "contrib"
projects[pagerer][version] = "1.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[purl][subdir] = "contrib"
projects[purl][version] = "1.0-beta1"

projects[realname][subdir] = "contrib"
projects[realname][version] = "1.0"

projects[services][subdir] = "contrib"
projects[services][version] = "3.3"

projects[services_views][subdir] = "contrib"
projects[services_views][version] = "1.0-beta2"

projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "2.1"

projects[spaces][subdir] = "contrib"
projects[spaces][version] = "3.0-alpha1+9-dev"
projects[spaces][patches][] = "https://raw.github.com/pinedrop/mediabase/master/patches/spaces_og_use_a_different_space_type_plugin.patch"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta6"
projects[views_data_export][patches][] = "http://drupal.org/files/views_data_export-Fix_Mysql_specific_code-1690438-4.patch"

projects[views_datasource][subdir] = "contrib"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.6"

; Themes
projects[omega][version] = "3.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mb-html5][download][type] = ""
projects[mb-html5][download][url] = ""
projects[mb-html5][type] = "theme"
projects[mb-html5][version] = "unknown"

; Modules
projects[kmaps_modules][type] = "module"
projects[kmaps_modules][download][type] = "git"
projects[kmaps_modules][download][url] = "https://github.com/shanti-uva/drupal_kmaps_modules.git"
projects[kmaps_modules][download][revision] = "9d1cd379a747a6c3e72b988457777c08d553e678"

projects[sarvaka_modules][type] = "module"
projects[sarvaka_modules][download][type] = "git"
projects[sarvaka_modules][download][url] = "git@github.com:shanti-uva/drupal_shanti_sarvaka_modules.git"
projects[sarvaka_modules][download][revision] = "9db63d9652ae5427cd5a9c1853db0f6ca5d760f2"

projects[kmaps_navigator][type] = "module"
projects[kmaps_navigator][download][type] = "git"
projects[kmaps_navigator][download][url] = "https://github.com/shanti-uva/drupal_kmaps_navigator.git"
projects[kmaps_navigator][download][branch] = "mediabase"
projects[kmaps_navigator][download][revision] = "5cb48e5c5e236f1b58ec99988ebad360903c6a98"

projects[transcripts_apachesolr][type] = "module"
projects[transcripts_apachesolr][download][type] = "git"
projects[transcripts_apachesolr][download][url] = "https://github.com/pinedrop/transcripts_apachesolr.git"
projects[transcripts_apachesolr][download][revision] = "a1c2656accef026f8a7640e5f08a32e627be615c"

projects[transcripts_ui][type] = "module"
projects[transcripts_ui][download][type] = "git"
projects[transcripts_ui][download][url] = "https://github.com/pinedrop/transcripts_ui.git"
projects[transcripts_ui][download][revision] = "a107d069922cb4847c9e0e751120af5cd7b065e0"

; Themes
projects[sarvaka_mediabase][type] = "theme"
projects[sarvaka_mediabase][download][type] = "git"
projects[sarvaka_mediabase][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_mediabase.git"
projects[sarvaka_mediabase][download][revision] = "4dd91b2717ac7cd4a22329b75a6b04370ac81078"

projects[shanti_sarvaka][type] = "theme"
projects[shanti_sarvaka][download][type] = "git"
projects[shanti_sarvaka][download][url] = "https://github.com/shanti-uva/drupal_shanti_sarvaka_theme.git"
projects[shanti_sarvaka][download][revision] = "29ddc4be224be6366e813dd86a5c7c837e05095d"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplehtmldom][download][type] = ""
libraries[simplehtmldom][download][url] = ""
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ajaxsolr][download][type] = ""
libraries[ajaxsolr][download][url] = ""
libraries[ajaxsolr][directory_name] = "ajaxsolr"
libraries[ajaxsolr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fancytree][download][type] = ""
libraries[fancytree][download][url] = ""
libraries[fancytree][directory_name] = "fancytree"
libraries[fancytree][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[saxon][download][type] = ""
libraries[saxon][download][url] = ""
libraries[saxon][directory_name] = "saxon"
libraries[saxon][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"


