; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.12"

; Modules
projects[views_bulk_operations][version] = "3.0-beta3"
projects[admin_menu][version] = "3.0-rc1"
projects[apachesolr][version] = "1.0-beta16"
projects[backup_migrate][version] = "2.2"
projects[ctools][version] = "1.x-dev"
projects[context][version] = "3.0-beta2"
projects[facetapi][version] = "1.0-rc2"
projects[date][version] = "2.0-alpha4"
projects[devel][version] = "1.2"
projects[diff][version] = "2.0"
projects[entity][version] = "1.x-dev"
projects[entityreference][version] = "1.0-beta4"
projects[facetapi_slider][version] = "1.x-dev"
projects[features][version] = "1.x-dev"
projects[field_collection][version] = "1.x-dev"
projects[field_group][version] = "1.x-dev"
projects[kaltura][version] = "2.0-beta1"
projects[job_scheduler][version] = "2.0-alpha2"
projects[masquerade][version] = "1.0-rc4"
projects[og][version] = "1.3"
projects[og_create_perms][version] = "1.0"
projects[pathauto][version] = "1.0"
projects[profile2][version] = "1.2"
projects[realname][version] = "1.0-rc2"
projects[shib_auth][version] = "4.0"
projects[strongarm][version] = "2.0-beta4"
projects[subform][version] = "1.0-alpha1"
projects[token][version] = "1.0-beta7"
projects[views][version] = "3.2"

; Themes
projects[omega][version] = "3.0"

; Git Repositories THESE ARE NOW BEING PULLED FROM THE SHELL SCRIPT  
projects[mediabase][download][type] = "git"
; projects[mediabase][download][url] = "git://github.com/pinedrop/mediabase.git"
projects[mediabase][subdir] = "sites/mediabase"
projects[mediabase][type] = "module"

projects[transcripts][download][type] = "git"
projects[transcripts][download][url] = "git://github.com/pinedrop/transcripts.git"
projects[transcripts][subdir] = "sites/mediabase/modules"
projects[transcripts][type] = "module"
